-- berean.db schema at migration version 42 (generated by scripts/dump-user-schema.ts)

CREATE TABLE ai_chats (
          id         TEXT PRIMARY KEY,
          title      TEXT NOT NULL,
          messages   TEXT NOT NULL,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL
        );

CREATE TABLE highlights (
          id         TEXT PRIMARY KEY,
          text_id    TEXT NOT NULL,
          book_id    TEXT NOT NULL,
          chapter    INTEGER NOT NULL,
          verse_num  INTEGER NOT NULL,
          start_word INTEGER,
          end_word   INTEGER,
          color      TEXT NOT NULL,
          label      TEXT,
          created_at INTEGER NOT NULL
        , start_char INTEGER, end_char INTEGER);

CREATE TABLE history (
          id            TEXT PRIMARY KEY,
          type          TEXT NOT NULL,
          title         TEXT NOT NULL,
          timestamp     INTEGER NOT NULL,
          session_id    TEXT,
          session_name  TEXT,
          book_id       TEXT,
          chapter       INTEGER,
          verse         INTEGER,
          note_id       TEXT,
          strongs_num   TEXT,
          video_id      TEXT,
          query         TEXT,
          parent_id     TEXT,
          import_source TEXT,
          import_count  INTEGER
        );

CREATE TABLE note_folders (
          id         TEXT PRIMARY KEY,
          name       TEXT NOT NULL,
          parent_id  TEXT,
          created_at INTEGER NOT NULL
        );

CREATE TABLE note_heading_collapse (
          note_id     TEXT NOT NULL,
          heading_key TEXT NOT NULL,
          collapsed   INTEGER NOT NULL DEFAULT 1,
          PRIMARY KEY (note_id, heading_key)
        );

CREATE TABLE note_thread_collapse (
          note_id    TEXT NOT NULL,
          thread_key TEXT NOT NULL,
          collapsed  INTEGER NOT NULL DEFAULT 1,
          PRIMARY KEY (note_id, thread_key)
        );

CREATE TABLE note_versions (
          id         TEXT PRIMARY KEY,
          note_id    TEXT NOT NULL,
          title      TEXT,
          content    TEXT NOT NULL DEFAULT '',
          kind       TEXT NOT NULL DEFAULT 'auto',
          created_at INTEGER NOT NULL
        );

CREATE TABLE notes (
          id         TEXT PRIMARY KEY,
          type       TEXT NOT NULL DEFAULT 'general',
          title      TEXT,
          content    TEXT NOT NULL DEFAULT '',
          verse_ref  TEXT,
          color      TEXT NOT NULL DEFAULT 'blue',
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL,
          tags       TEXT NOT NULL DEFAULT '[]'
        , imported_at INTEGER, folder_id TEXT, text_id TEXT DEFAULT 'kjva', idiom_term TEXT, idiom_meaning TEXT, idiom_aliases TEXT, idiom_auto_variants INTEGER DEFAULT 0, idiom_data TEXT, status TEXT, deleted_at INTEGER, icon TEXT, pinned INTEGER DEFAULT 0);

CREATE VIRTUAL TABLE notes_fts USING fts5(
          title,
          content,
          content='notes',
          content_rowid='rowid',
          tokenize='unicode61'
        );

CREATE TABLE 'notes_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;

CREATE TABLE 'notes_fts_data'(id INTEGER PRIMARY KEY, block BLOB);

CREATE TABLE 'notes_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);

CREATE TABLE 'notes_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;

CREATE TABLE pdf_highlights (
          id          TEXT PRIMARY KEY,
          pdf_id      TEXT NOT NULL,
          page        INTEGER NOT NULL,
          rects_json  TEXT NOT NULL,
          color       TEXT NOT NULL,
          text        TEXT NOT NULL DEFAULT '',
          note        TEXT,
          created_at  INTEGER NOT NULL
        );

CREATE TABLE pdfs (
          id          TEXT PRIMARY KEY,
          title       TEXT NOT NULL,
          filename    TEXT NOT NULL,
          page_count  INTEGER NOT NULL DEFAULT 0,
          file_size   INTEGER NOT NULL DEFAULT 0,
          imported_at INTEGER NOT NULL
        );

CREATE TABLE playlist_items (
          id          TEXT PRIMARY KEY,
          playlist_id TEXT NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
          position    INTEGER NOT NULL,
          book_id     TEXT NOT NULL,
          chapter     INTEGER NOT NULL,
          start_verse INTEGER NOT NULL DEFAULT 1,
          end_verse   INTEGER,
          text_id     TEXT NOT NULL
        );

CREATE TABLE playlists (
          id         TEXT PRIMARY KEY,
          name       TEXT NOT NULL,
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        );

CREATE TABLE schema_version (version INTEGER NOT NULL);

CREATE TABLE settings (
          key   TEXT PRIMARY KEY,
          value TEXT NOT NULL
        );

CREATE TABLE tag_edges (
          id            TEXT PRIMARY KEY,
          source_tag_id TEXT NOT NULL REFERENCES verse_tags(id) ON DELETE CASCADE,
          target_tag_id TEXT NOT NULL REFERENCES verse_tags(id) ON DELETE CASCADE,
          arrows        TEXT NOT NULL DEFAULT 'none',   -- 'none' | 'forward' | 'backward' | 'both'
          color         TEXT,                            -- slot index as string, or literal; NULL = neutral
          dashed        INTEGER NOT NULL DEFAULT 0,
          note          TEXT NOT NULL DEFAULT '',
          created_at    INTEGER NOT NULL,
          updated_at    INTEGER NOT NULL
        );

CREATE TABLE trail_collapse (
          scope      TEXT NOT NULL,
          key        TEXT NOT NULL,
          collapsed  INTEGER NOT NULL DEFAULT 1,
          updated_at INTEGER NOT NULL,
          PRIMARY KEY (scope, key)
        );

CREATE TABLE trail_connections (
          id                    TEXT PRIMARY KEY,
          trail_session_id      TEXT NOT NULL,
          from_node_id          TEXT NOT NULL,
          to_kind               TEXT NOT NULL,     -- 'chapter'|'lexicon'|'note'|'video'|'compare'
          to_book_id            TEXT,
          to_chapter            INTEGER,
          to_verse              INTEGER,
          to_strongs_num        TEXT,
          to_note_id            TEXT,
          to_video_id           TEXT,
          clarity_tier          INTEGER NOT NULL,  -- 1 (clear) | 2 (soft) | 3 (ambiguous)
          reason_text           TEXT,
          reason_tags           TEXT,              -- JSON array
          verse_pin_from        INTEGER,
          verse_pin_to          INTEGER,
          weight                TEXT NOT NULL DEFAULT 'full',  -- 'full' | 'glance'
          strongs_depth         TEXT,              -- 'click' | 'occurrences' | 'related'
          cluster_id            TEXT,
          dismissed_prompt_at   INTEGER,
          created_at            INTEGER NOT NULL
        , origin_verse_pin_from INTEGER, origin_verse_pin_to INTEGER, from_connection_id TEXT, chain_depth INTEGER NOT NULL DEFAULT 0, to_verse_end INTEGER, ties TEXT, user_note TEXT, ties_from TEXT, ties_to TEXT, is_branch INTEGER NOT NULL DEFAULT 0, is_branch_return INTEGER NOT NULL DEFAULT 0);

CREATE TABLE trail_embeddings (
          id          TEXT PRIMARY KEY,
          ref_type    TEXT NOT NULL,   -- 'connection_reason' | 'lexicon_gloss' | 'recap'
          ref_id      TEXT NOT NULL,
          source_text TEXT NOT NULL,
          vector      BLOB NOT NULL,   -- Float32Array, serialized
          updated_at  INTEGER NOT NULL
        );

CREATE TABLE trail_nodes (
          id                  TEXT PRIMARY KEY,
          trail_session_id    TEXT NOT NULL,
          book_id             TEXT NOT NULL,
          chapter             INTEGER NOT NULL,
          order_index         INTEGER NOT NULL,
          anchor_started_at   INTEGER NOT NULL,
          anchor_ended_at     INTEGER,            -- NULL while still the active anchor
          cached_subnote      TEXT,
          origin_label        TEXT
        , revisit_of_node_id TEXT, promoted_from_connection_id TEXT, translation TEXT, cluster_id TEXT, is_topic_break INTEGER NOT NULL DEFAULT 0);

CREATE TABLE trail_notes (
          id               TEXT PRIMARY KEY,
          trail_session_id TEXT NOT NULL,
          kind             TEXT NOT NULL DEFAULT 'annotation',
          anchor_node_id   TEXT,
          order_index      INTEGER NOT NULL DEFAULT 0,
          title            TEXT,
          body             TEXT NOT NULL DEFAULT '',
          width            INTEGER,
          height           INTEGER,
          note_id          TEXT,
          color            TEXT,
          created_at       INTEGER NOT NULL,
          updated_at       INTEGER NOT NULL
        , offset_x INTEGER, offset_y INTEGER);

CREATE TABLE trail_paused_intervals (
          id                TEXT PRIMARY KEY,
          trail_session_id  TEXT NOT NULL,
          paused_at         INTEGER NOT NULL,
          resumed_at        INTEGER               -- NULL while still paused
        );

CREATE TABLE trail_sessions (
          id                   TEXT PRIMARY KEY,
          name                 TEXT NOT NULL,
          status               TEXT NOT NULL,        -- 'live' | 'paused' | 'ended'
          possibly_accidental  INTEGER DEFAULT 0,
          recap_text           TEXT,
          recap_user_edited    INTEGER DEFAULT 0,     -- once 1, auto-recap never overwrites it
          created_at           INTEGER NOT NULL,
          updated_at           INTEGER NOT NULL
        , sort_order INTEGER);

CREATE TABLE trail_tag_members (
          tag_id           TEXT NOT NULL REFERENCES trail_tags(id) ON DELETE CASCADE,
          trail_session_id TEXT NOT NULL,
          created_at       INTEGER NOT NULL,
          PRIMARY KEY (tag_id, trail_session_id)
        );

CREATE TABLE trail_tags (
          id         TEXT PRIMARY KEY,
          name       TEXT NOT NULL,
          color      TEXT,
          sort_order INTEGER,
          created_at INTEGER NOT NULL
        );

CREATE TABLE verse_tag_members (
          id         TEXT PRIMARY KEY,
          tag_id     TEXT NOT NULL REFERENCES verse_tags(id) ON DELETE CASCADE,
          kind       TEXT NOT NULL DEFAULT 'verses',
          ranges     TEXT NOT NULL,
          label      TEXT NOT NULL,
          created_at INTEGER NOT NULL
        );

CREATE TABLE verse_tag_verse (
          tag_id    TEXT NOT NULL,
          member_id TEXT NOT NULL,
          book_id   TEXT NOT NULL,
          chapter   INTEGER NOT NULL,
          verse     INTEGER NOT NULL,
          PRIMARY KEY (tag_id, book_id, chapter, verse, member_id)
        );

CREATE TABLE verse_tags (
          id         TEXT PRIMARY KEY,
          name       TEXT NOT NULL,
          color      TEXT,
          sort_order INTEGER,
          created_at INTEGER NOT NULL
        , color_slot INTEGER, graph_x REAL, graph_y REAL, graph_pinned INTEGER NOT NULL DEFAULT 0);

CREATE TABLE workspaces (
          id          TEXT PRIMARY KEY,
          name        TEXT NOT NULL,
          layout_json TEXT NOT NULL,
          created_at  INTEGER NOT NULL
        , state_json TEXT);

CREATE TABLE youtube_sync (
          channel_handle TEXT PRIMARY KEY,
          last_full_sync TEXT,
          last_refresh   TEXT
        );

CREATE TABLE youtube_transcript_segments (
          id       INTEGER PRIMARY KEY,
          video_id TEXT NOT NULL
            REFERENCES youtube_transcripts(video_id) ON DELETE CASCADE,
          start_ms INTEGER NOT NULL,
          dur_ms   INTEGER NOT NULL DEFAULT 0,
          text     TEXT NOT NULL
        );

CREATE TABLE youtube_transcripts (
          video_id      TEXT PRIMARY KEY,
          lang          TEXT NOT NULL DEFAULT 'en',
          source        TEXT NOT NULL DEFAULT 'timedtext',
          fetched_at    INTEGER NOT NULL,
          segment_count INTEGER NOT NULL DEFAULT 0,
          duration_ms   INTEGER NOT NULL DEFAULT 0,
          error         TEXT
        );

CREATE VIRTUAL TABLE youtube_transcripts_fts USING fts5(
          text,
          content='youtube_transcript_segments',
          content_rowid='id',
          tokenize='unicode61'
        );

CREATE TABLE 'youtube_transcripts_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;

CREATE TABLE 'youtube_transcripts_fts_data'(id INTEGER PRIMARY KEY, block BLOB);

CREATE TABLE 'youtube_transcripts_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);

CREATE TABLE 'youtube_transcripts_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;

CREATE TABLE youtube_videos (
          video_id       TEXT PRIMARY KEY,
          title          TEXT NOT NULL,
          published      TEXT NOT NULL,
          channel_name   TEXT NOT NULL,
          channel_handle TEXT NOT NULL,
          thumbnail_url  TEXT NOT NULL,
          type           TEXT NOT NULL,
          is_live_now    INTEGER NOT NULL DEFAULT 0,
          fetched_at     TEXT NOT NULL
        , duration_seconds INTEGER NOT NULL DEFAULT 0, is_starred INTEGER NOT NULL DEFAULT 0, description TEXT NOT NULL DEFAULT '');

CREATE TABLE youtube_watch_history (
          video_id         TEXT PRIMARY KEY,
          position_seconds REAL NOT NULL DEFAULT 0,
          last_watched     TEXT NOT NULL,
          title            TEXT NOT NULL DEFAULT '',
          channel_name     TEXT NOT NULL DEFAULT '',
          thumbnail_url    TEXT NOT NULL DEFAULT ''
        );

CREATE INDEX idx_ai_chats_updated ON ai_chats(updated_at DESC);

CREATE INDEX idx_highlights_verse ON highlights(text_id, book_id, chapter, verse_num);

CREATE INDEX idx_history_ts ON history(timestamp DESC);

CREATE INDEX idx_note_folders_parent ON note_folders(parent_id);

CREATE INDEX idx_note_versions_note ON note_versions(note_id, created_at DESC);

CREATE INDEX idx_notes_deleted_at ON notes(deleted_at);

CREATE INDEX idx_notes_updated ON notes(updated_at DESC);

CREATE INDEX idx_notes_verse ON notes(verse_ref);

CREATE INDEX idx_pdf_hl_pdf ON pdf_highlights(pdf_id);

CREATE INDEX idx_playlist_items_playlist ON playlist_items(playlist_id, position);

CREATE UNIQUE INDEX idx_tag_edges_pair ON tag_edges(source_tag_id, target_tag_id);

CREATE INDEX idx_tag_edges_src ON tag_edges(source_tag_id);

CREATE INDEX idx_tag_edges_tgt ON tag_edges(target_tag_id);

CREATE INDEX idx_trail_conn_dest ON trail_connections(to_book_id, to_chapter);

CREATE INDEX idx_trail_conn_parent ON trail_connections(from_connection_id);

CREATE INDEX idx_trail_conn_session ON trail_connections(trail_session_id, created_at);

CREATE INDEX idx_trail_embeddings_ref ON trail_embeddings(ref_type, ref_id);

CREATE INDEX idx_trail_nodes_session ON trail_nodes(trail_session_id, order_index);

CREATE INDEX idx_trail_notes_anchor ON trail_notes(anchor_node_id);

CREATE INDEX idx_trail_notes_session ON trail_notes(trail_session_id);

CREATE INDEX idx_trail_paused_session ON trail_paused_intervals(trail_session_id);

CREATE UNIQUE INDEX idx_trail_tags_name ON trail_tags(name COLLATE NOCASE);

CREATE INDEX idx_ttm_session ON trail_tag_members(trail_session_id);

CREATE UNIQUE INDEX idx_verse_tags_name ON verse_tags(name COLLATE NOCASE);

CREATE INDEX idx_vtm_tag ON verse_tag_members(tag_id);

CREATE INDEX idx_vtv_loc ON verse_tag_verse(book_id, chapter);

CREATE INDEX idx_vtv_tag ON verse_tag_verse(tag_id);

CREATE INDEX idx_yt_handle   ON youtube_videos(channel_handle);

CREATE INDEX idx_yt_published ON youtube_videos(published DESC);

CREATE INDEX idx_yt_seg_video
          ON youtube_transcript_segments(video_id, start_ms);

CREATE INDEX idx_yt_transcripts_fetched
          ON youtube_transcripts(fetched_at DESC);

CREATE TRIGGER notes_ad
        AFTER DELETE ON notes BEGIN
          INSERT INTO notes_fts(notes_fts, rowid, title, content)
          VALUES ('delete', old.rowid, old.title, old.content);
        END;

CREATE TRIGGER notes_ai
        AFTER INSERT ON notes BEGIN
          INSERT INTO notes_fts(rowid, title, content)
          VALUES (new.rowid, new.title, new.content);
        END;

CREATE TRIGGER notes_au
        AFTER UPDATE ON notes BEGIN
          INSERT INTO notes_fts(notes_fts, rowid, title, content)
          VALUES ('delete', old.rowid, old.title, old.content);
          INSERT INTO notes_fts(rowid, title, content)
          VALUES (new.rowid, new.title, new.content);
        END;

CREATE TRIGGER yt_seg_ad
        AFTER DELETE ON youtube_transcript_segments BEGIN
          INSERT INTO youtube_transcripts_fts(youtube_transcripts_fts, rowid, text)
          VALUES ('delete', old.id, old.text);
        END;

CREATE TRIGGER yt_seg_ai
        AFTER INSERT ON youtube_transcript_segments BEGIN
          INSERT INTO youtube_transcripts_fts(rowid, text)
          VALUES (new.id, new.text);
        END;

CREATE TRIGGER yt_seg_au
        AFTER UPDATE ON youtube_transcript_segments BEGIN
          INSERT INTO youtube_transcripts_fts(youtube_transcripts_fts, rowid, text)
          VALUES ('delete', old.id, old.text);
          INSERT INTO youtube_transcripts_fts(rowid, text)
          VALUES (new.id, new.text);
        END;

