#!/usr/bin/env node
/**
 * Writes ios/App/Identity.xcconfig (gitignored) for the app identity being built
 * (config/app-identity.json): BEREAN_IDENTITY=production (default) → Berean, com.berean.app;
 * BEREAN_IDENTITY=development → Berean Dev, com.berean.app.dev. Berean.xcconfig includes it after
 * Signing.xcconfig, so identity values can never come from anywhere else. Run by `npm run ios:sync`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const name = process.env.BEREAN_IDENTITY ?? 'production'
const config = JSON.parse(readFileSync(resolve(process.cwd(), 'config/app-identity.json'), 'utf8'))
const id = config.identities[name]
if (!id || (name !== 'production' && name !== 'development')) {
  console.error(`[ios] BEREAN_IDENTITY must be "production" or "development", got "${name}"`)
  process.exit(1)
}
const lines = [
  '// Generated by scripts/ios/identity.mjs from config/app-identity.json — do not edit by hand.',
  `BEREAN_IDENTITY = ${name}`,
  `BEREAN_BUNDLE_ID = ${id.bundleId}`,
  `BEREAN_DISPLAY_NAME = ${id.appName}`,
  `BEREAN_ICLOUD_CONTAINER = ${id.cloudContainer}`,
  `BEREAN_APP_GROUP = ${id.appGroup}`,
  `BEREAN_URL_SCHEME = ${id.urlScheme}`,
  `BEREAN_PDF_URL_SCHEME = ${id.pdfUrlScheme}`,
  '',
]
writeFileSync(resolve(process.cwd(), 'ios/App/Identity.xcconfig'), lines.join('\n'))
console.log(`[ios] Identity.xcconfig → ${name} (${id.appName}, ${id.bundleId}, ${id.cloudContainer})`)
