#!/usr/bin/env node
/**
 * Writes the identity xcconfigs (gitignored) from config/app-identity.json:
 *
 *  - ios/App/Identity.xcconfig — the identity of RELEASE builds (archives):
 *    BEREAN_IDENTITY=production (default) → Berean, com.berean.app;
 *    BEREAN_IDENTITY=development → Berean Dev, com.berean.app.dev (`ios:archive:dev`).
 *  - ios/App/IdentityDevelopment.xcconfig — ALWAYS Berean Dev. BereanDebug.xcconfig includes it
 *    last, so every DEBUG build (Xcode ▶ Run on an iPhone or simulator, `ios:build`, `ios:device`)
 *    is com.berean.app.dev and installs NEXT TO the App Store / TestFlight Berean, never over it
 *    (TEST 2026-10-01: `ios:sync` + Run used to install com.berean.app over production).
 *
 * Berean.xcconfig includes Identity.xcconfig after Signing.xcconfig, so identity values can never
 * come from anywhere else. Run by `npm run ios:sync` / `ios:sync:dev`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const name = process.env.BEREAN_IDENTITY ?? 'production'
const config = JSON.parse(readFileSync(resolve(process.cwd(), 'config/app-identity.json'), 'utf8'))
const id = config.identities[name]
if (!id || (name !== 'production' && name !== 'development')) {
  console.error(`[ios] BEREAN_IDENTITY must be "production" or "development", got "${name}"`)
  process.exit(1)
}
const lines = [
  '// Generated by scripts/ios/identity.mjs from config/app-identity.json — do not edit by hand.',
  `BEREAN_IDENTITY = ${name}`,
  `BEREAN_BUNDLE_ID = ${id.bundleId}`,
  `BEREAN_DISPLAY_NAME = ${id.appName}`,
  `BEREAN_ICLOUD_CONTAINER = ${id.cloudContainer}`,
  `BEREAN_APP_GROUP = ${id.appGroup}`,
  `BEREAN_URL_SCHEME = ${id.urlScheme}`,
  `BEREAN_PDF_URL_SCHEME = ${id.pdfUrlScheme}`,
  '',
]
writeFileSync(resolve(process.cwd(), 'ios/App/Identity.xcconfig'), lines.join('\n'))
console.log(`[ios] Identity.xcconfig (Release / archive) → ${name} (${id.appName}, ${id.bundleId}, ${id.cloudContainer})`)

const dev = config.identities.development
writeFileSync(resolve(process.cwd(), 'ios/App/IdentityDevelopment.xcconfig'), [
  '// Generated by scripts/ios/identity.mjs from config/app-identity.json — do not edit by hand.',
  '// Included LAST by BereanDebug.xcconfig: every Debug build (Xcode Run) is Berean Dev.',
  'BEREAN_IDENTITY = development',
  `BEREAN_BUNDLE_ID = ${dev.bundleId}`,
  `BEREAN_DISPLAY_NAME = ${dev.appName}`,
  `BEREAN_ICLOUD_CONTAINER = ${dev.cloudContainer}`,
  `BEREAN_APP_GROUP = ${dev.appGroup}`,
  `BEREAN_URL_SCHEME = ${dev.urlScheme}`,
  `BEREAN_PDF_URL_SCHEME = ${dev.pdfUrlScheme}`,
  '',
].join('\n'))
console.log(`[ios] IdentityDevelopment.xcconfig (Debug / Xcode Run) → development (${dev.appName}, ${dev.bundleId})`)
