#!/usr/bin/env node
/**
 * Writes ios/App/Version.xcconfig from package.json so the iOS MARKETING_VERSION always matches
 * the desktop version (R123). CURRENT_PROJECT_VERSION (the build number) is bumped only by
 * `npm run ios:bump-build`; TestFlight requires it to increase for every upload of the same
 * marketing version.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const pkg = JSON.parse(readFileSync(resolve(process.cwd(), 'package.json'), 'utf8'))
const file = resolve(process.cwd(), 'ios/App/Version.xcconfig')
let build = 1
if (existsSync(file)) {
  const m = readFileSync(file, 'utf8').match(/CURRENT_PROJECT_VERSION = (\d+)/)
  if (m) build = Number(m[1])
}
if (process.argv.includes('--bump-build')) build += 1
writeFileSync(file, `// Generated by scripts/ios/version.mjs from package.json — do not edit by hand.\nMARKETING_VERSION = ${pkg.version}\nCURRENT_PROJECT_VERSION = ${build}\n`)
console.log(`[ios] Version.xcconfig → ${pkg.version} (${build})`)
