#!/usr/bin/env python3
"""
Adds REVERSE-direction indexes to data/cross_references.db and data/tske_refs.db.

Both DBs shipped with only a forward index (from_book, from_ch, from_vs) — see idx_from /
idx_tske_from in their own CREATE INDEX statements. `electron/ipc/crossrefs.ts`'s
getIncomingCrossRefsForVerse/getIncomingTskeForVerse (added for aiLookup.ts's "what quotes/
references verse X" reverse lookup) query the OPPOSITE direction — `to_book`/`to_ch`/`to_vs` — and
without a matching index those are full table scans: 300k+ rows in cross_references.db's `refs`
table, 670k+ in tske_refs.db's `tske_refs` table.

Both app DBs are opened `{ readonly: true }` at runtime (see crossrefs.ts) and are gitignored
build artifacts (see .gitignore's `*.db`), not generated by any script in this repo — they're
pre-built third-party imports. So there is no "regenerate from source" step these indexes can be
folded into; this script is the one-time (idempotent — CREATE INDEX IF NOT EXISTS) fix, meant to
be run once against data/*.db before packaging a release, same as any other data/ prep step. The
app itself never needs to run this — a missing index just means a slower (not broken) reverse
lookup, so nothing at runtime depends on it having been run; this is a data-quality/perf fix, not
a correctness dependency.

Usage: python3 scripts/add_crossref_reverse_indexes.py
Run from the project root.
"""

import os
import sqlite3
import sys

DB_SPECS = [
    ("data/cross_references.db", "refs", "idx_to", ["to_book", "to_ch", "to_vs"]),
    ("data/tske_refs.db", "tske_refs", "idx_tske_to", ["to_book", "to_ch", "to_vs", "is_reciprocal"]),
]


def add_index(path: str, table: str, index_name: str, columns: list[str]) -> None:
    if not os.path.exists(path):
        print(f"skip: {path} not found")
        return
    conn = sqlite3.connect(path)
    try:
        cols = ", ".join(columns)
        conn.execute(f"CREATE INDEX IF NOT EXISTS {index_name} ON {table}({cols})")
        conn.commit()
        print(f"ok: {index_name} on {path}::{table}({cols})")
    finally:
        conn.close()


if __name__ == "__main__":
    for path, table, index_name, columns in DB_SPECS:
        add_index(path, table, index_name, columns)
