/**
 * Dump the berean.db schema produced by the SHARED migration history (src/platform/db/
 * bereanMigrations.ts) to stdout as SQL. Used to keep docs/mobile/audit/schema-v<N>.sql current
 * whenever a migration is added (docs/mobile/database.md §5).
 *
 *   npx tsx scripts/dump-user-schema.ts > docs/mobile/audit/schema-v42.sql
 */
import { openNodeSqlite } from '../electron/db/adapters/nodeSqliteAdapter'
import { runMigrations, BEREAN_SCHEMA_VERSION } from '../src/platform/db/bereanMigrations'

async function main() {
  const origLog = console.log
  console.log = () => {}   // silence the migrations' progress lines
  const db = openNodeSqlite(':memory:', 'schema-dump')
  await runMigrations(db)
  console.log = origLog
  const rows = await db.all<{ type: string; name: string; sql: string | null }>(
    "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END, name",
  )
  process.stdout.write(`-- berean.db schema at migration version ${BEREAN_SCHEMA_VERSION} (generated by scripts/dump-user-schema.ts)\n\n`)
  for (const r of rows) process.stdout.write(`${r.sql};\n\n`)
}
main().catch((err) => { console.error(err); process.exit(1) })
