#!/usr/bin/env python3
"""
scripts/train_ibm_model1.py

A fundamentally different approach from build_lxx_brenton_strongs.py's gloss-keyword
heuristic: IBM Model 1, the classic statistical word-alignment model (Brown et al.
1993), trained via EM across the WHOLE corpus at once rather than verse-by-verse.

Instead of asking "does this English word share a keyword with this G-number's
short_def" (which only ever looks at ONE verse and ONE dictionary gloss at a time),
this asks "across all 27,000+ verses, which Greek word does this English word
actually keep showing up paired with" — a real statistical signal that the
gloss-matching heuristic has no way to use at all. It only ever needs the raw
(English text, Greek text_tagged) verse pairs; the Strong's dictionary isn't
involved in training at all (only afterward, to translate a chosen Greek WORD back
to its already-known G-number for output).

Model: t(e|f) = probability English word e is generated by Greek word f (or the
per-verse NULL token, for English words with no true Greek counterpart — inserted
copulas, "which", etc.). EM alternates:
  E-step: for every (e, f) pair actually co-occurring in a verse, compute the
          normalized alignment probability a(f|e) = t(e|f) / sum_f' t(e|f') over
          just THAT verse's own Greek words + NULL, and accumulate expected counts.
  M-step: re-estimate t(e|f) = count(e,f) / count(f) from those accumulated counts.
Model 1's EM is convex (guaranteed to converge to the same global optimum regardless
of initialization), so uniform initialization (implicit here: an unseen pair defaults
to weight 1.0 before normalization on the first pass) is standard and sufficient.

Output: a JSON translation table {greek_word: {english_word: prob, ...}, ...} plus
"NULL": {...} for the null-alignment probabilities. Saved to
scripts/ibm_model1_table.json (gitignored — regenerate by re-running this script;
it's a few hundred MB and doesn't belong in git).

Usage:
  python3 scripts/train_ibm_model1.py [--iterations 8] [--sample N]

Read-only against the databases — writes only the JSON table file.
"""
import argparse
import json
import re
import sqlite3
import time
from collections import defaultdict
from pathlib import Path

BRENTON_DB = Path(__file__).parent.parent / 'data' / 'lxx_brenton.db'
LXX_DB = Path(__file__).parent.parent / 'data' / 'lxx.db'
OUT_PATH = Path(__file__).parent / 'ibm_model1_table.json'

NULL_TOKEN = '\x00NULL'

WORD_RE = re.compile(r"^[^A-Za-z']*([A-Za-z'][A-Za-z'-]*)[^A-Za-z'-]*$")


def clean_english(tok: str) -> str | None:
    m = WORD_RE.match(tok)
    return m.group(1).lower() if m else None


def parse_greek_words(tagged: str) -> list[str]:
    """Greek surface forms only (lowercased), NOT their G-numbers — the co-occurrence
    model operates on word forms; G-numbers are looked up again at inference time from
    whichever Greek token (by position) actually got aligned to."""
    out = []
    for tok in tagged.split():
        m = re.match(r'^(.+?)\{G\d*\}$', tok)
        out.append((m.group(1) if m else tok).lower())
    return out


def load_pairs(sample: int | None) -> list[tuple[list[str], list[str]]]:
    brenton_db = sqlite3.connect(str(BRENTON_DB))
    lxx_db = sqlite3.connect(str(LXX_DB))
    rahlfs: dict[tuple[str, int, int], list[str]] = {}
    for bid, ch, vs, tagged in lxx_db.execute(
            "SELECT book_id, chapter, verse_num, text_tagged FROM verses "
            "WHERE text_tagged IS NOT NULL AND text_tagged != ''"):
        rahlfs[(bid, ch, vs)] = parse_greek_words(tagged)

    query = "SELECT book_id, chapter, verse_num, text FROM verses ORDER BY id"
    if sample:
        query += f" LIMIT {sample}"
    pairs = []
    for bid, ch, vs, text in brenton_db.execute(query):
        grk = rahlfs.get((bid, ch, vs))
        if not grk:
            continue
        eng = [w for w in (clean_english(t) for t in text.split()) if w]
        if not eng:
            continue
        pairs.append((eng, grk))
    brenton_db.close()
    lxx_db.close()
    return pairs


def train(pairs: list[tuple[list[str], list[str]]], iterations: int) -> dict[str, dict[str, float]]:
    t: dict[str, dict[str, float]] = {}

    for it in range(iterations):
        t0 = time.time()
        count: dict[str, dict[str, float]] = defaultdict(lambda: defaultdict(float))
        total_f: dict[str, float] = defaultdict(float)

        for eng, grk in pairs:
            f_words = grk + [NULL_TOKEN]
            for e in eng:
                weights = [t.get(f, {}).get(e, 1.0) for f in f_words]
                z = sum(weights)
                if z <= 0:
                    continue
                for f, w in zip(f_words, weights):
                    a = w / z
                    count[f][e] += a
                    total_f[f] += a

        new_t: dict[str, dict[str, float]] = {}
        for f, ecounts in count.items():
            tf = total_f[f]
            if tf <= 0:
                continue
            new_t[f] = {e: c / tf for e, c in ecounts.items()}
        t = new_t
        print(f'  iteration {it + 1}/{iterations}: {len(t)} Greek word-forms, '
              f'{sum(len(v) for v in t.values())} (f,e) pairs, {time.time() - t0:.1f}s')

    return t


OUT_PATH_REV = Path(__file__).parent / 'ibm_model1_table_reverse.json'


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--iterations', type=int, default=8)
    ap.add_argument('--sample', type=int, help='only train on the first N verses (for a quick timing/sanity run)')
    args = ap.parse_args()

    print('Loading verse pairs …')
    pairs = load_pairs(args.sample)
    print(f'  {len(pairs)} verse pairs')

    # Forward: t(english | greek) — "which English word does this Greek word tend to produce."
    print(f'Training forward IBM Model 1 (english | greek), {args.iterations} iterations …')
    t = train(pairs, args.iterations)
    print(f'Writing {OUT_PATH} …')
    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        json.dump(t, f, ensure_ascii=False)

    # Reverse: t(greek | english) — trained with the roles of the two sides swapped. A pure
    # forward-only model has a well-known weakness ("garbage collection"): a very frequent
    # English word (he/the/and) can end up as the top "translation" for MANY different Greek
    # words simply because it co-occurs with almost everything, crowding out a more specific
    # but less frequent real translation (confirmed here: ἐποίησεν's top choice became "he"
    # instead of "made" after enough iterations). The reverse direction doesn't share that bias
    # — a genuine garbage-collector English word has LOW t(that specific greek word | itself),
    # since from ITS side, dozens of OTHER Greek words are just as good a match. Combining both
    # directions at inference time (see build_lxx_ibm_aligner.py) suppresses this.
    reversed_pairs = [(grk, eng) for eng, grk in pairs]
    print(f'Training reverse IBM Model 1 (greek | english), {args.iterations} iterations …')
    t_rev = train(reversed_pairs, args.iterations)
    print(f'Writing {OUT_PATH_REV} …')
    with open(OUT_PATH_REV, 'w', encoding='utf-8') as f:
        json.dump(t_rev, f, ensure_ascii=False)
    print('Done.')

    # Sanity spot-check: a handful of well-known Greek words should have a sane top
    # English translation given by the model, independent of anything in strongs_greek.db.
    print('\n=== Spot-check: top English translation per Greek word (forward only) ===')
    for grk_word in ['θεὸς', 'θεός', 'κύριος', 'ποιέω', 'ἐποίησεν', 'εἶπεν', 'ἄνθρωπος']:
        row = t.get(grk_word)
        if not row:
            print(f'  {grk_word}: (not seen)')
            continue
        top = sorted(row.items(), key=lambda kv: -kv[1])[:5]
        print(f'  {grk_word}: {top}')


if __name__ == '__main__':
    main()
