/**
 * Berean design-system primitives — see docs/design-system.md.
 * Import from '@/components/ui' rather than deep paths.
 */
export { cx } from './cx'
export { ControlSurfaceContext, useControlSurface, ControlGroupContext, useInControlGroup, ControlShapeContext, type ControlSurface, type ControlShape } from './surface'
export { ControlGroup, type ControlGroupProps } from './ControlGroup'
export { OverflowGroup, OverflowSection, type OverflowGroupProps, type OverflowItemMeta } from './OverflowGroup'
export { TitleControl, type TitleControlProps } from './TitleControl'
export { AlertSheet, type AlertSheetProps } from './AlertSheet'
export { Badge, type BadgeProps } from './Badge'
export { CompactMetrics, CompactMetricsContext, useCompactMetrics, type ControlSize } from './metrics'
export { Button, type ButtonProps, type ButtonVariant, type ButtonSize } from './Button'
export { IconButton, type IconButtonProps, type IconButtonSize } from './IconButton'
export { SegmentedControl, type SegmentedControlProps, type SegmentOption } from './SegmentedControl'
export { MenuSurface, MenuItem, MenuSeparator, MenuLabel, MenuGroup, MenuSub, type MenuItemProps } from './Menu'
export { useContextMenu, type ContextMenuState } from './ContextMenu'
export { TabStrip, type TabStripItem, type TabStripProps } from './TabStrip'
export { ScrollContainer, type ScrollContainerProps } from './ScrollContainer'
export { ResizeHandle, type ResizeHandleProps } from './ResizeHandle'
export { PopoverSurface, Popover, PopoverTrigger, PopoverAnchor, PopoverClose } from './PopoverSurface'
export { Sheet, SheetClose, type SheetProps, type SheetSize } from './Sheet'
export { TextField, SearchField, TextArea, type TextFieldProps, type SearchFieldProps, type TextAreaProps } from './TextField'
export { Select, type SelectProps, type SelectOption } from './Select'
export { Tooltip } from './Tooltip'
export { EmptyState } from './EmptyState'
export { SectionLabel } from './SectionLabel'
export { SectionHeader } from './SectionHeader'
export { RefChip, type RefChipVariant } from './RefChip'
export { Divider } from './Divider'
export { Toolbar, type ToolbarProps } from './Toolbar'
export { ToolbarSpacer, type ToolbarSpacerProps } from './ToolbarSpacer'
export { ListRow, type ListRowProps } from './ListRow'
export { Chip, type ChipProps } from './Chip'
export { Checkbox, Radio, type CheckboxProps, type RadioProps } from './Checkbox'
export { Slider, type SliderProps } from './Slider'
export { OptionCard, type OptionCardProps } from './OptionCard'
export { CardButton, type CardButtonProps, type CardButtonSurface } from './CardButton'
export { DisclosureRow, type DisclosureRowProps } from './DisclosureRow'
export { ColorSwatchRow, type Swatch } from './ColorSwatchRow'
export { default as Switch } from '@/components/shell/Switch'
export { default as ActionPillGroup } from '@/components/shell/ActionPillGroup'
export { default as Kbd } from '@/components/shell/ShortcutKeys'
